### ISSUE TITLE
Precompile issue for ContinuumWorld

### ISSUE THREAD

**Issue by felixmg312** [JuliaPOMDP/ContinuumWorld.jl#16]
Hi, I am currently facing an issue when trying to precompile ContinuumWorld when fixing the workflow for precompile. The error is like this:

 1 dependency errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the package
[ Info: We haven't cleaned this depot up for a bit, running Pkg.gc()...
      Active manifest files: 3 found
      Active artifact files: 71 found
      Active scratchspaces: 5 found
     Deleted no artifacts, repos, packages or scratchspaces
Precompiling project...
  ✗ ContinuumWorld
  0 dependencies successfully precompiled in 16 seconds. 181 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

ContinuumWorld [5cbb95a3-277b-5373-895a-7e14bd91b3cc]

Failed to precompile ContinuumWorld [5cbb95a3-277b-5373-895a-7e14bd91b3cc] to /home/runner/.julia/compiled/v1.8/ContinuumWorld/jl_9qlwbz.
┌ Warning: For saving to png with the `Plotly` backend `PlotlyBase` and `PlotlyKaleido` need to be installed.
│   err = Evaluation into the closed module `Plots` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Plots` with `eval` during precompilation - don't do this.
└ @ Plots ~/.julia/packages/Plots/nqFaB/src/backends.jl:545
ERROR: LoadError: Evaluation into the closed module `Plots` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `Plots` with `eval` during precompilation - don't do this.

**Comment by zsunberg** [comment]
@felixmg312 sorry about this and thanks for reporting. This repo will need a bit of work to update the things needed for Plotly and to fix all of the CompatHelper issues. If you have the expertise and want to take a stab at fixing it, that would be super helpful, otherwise I will try to fix it later this week.

**Comment by felixmg312** [comment]
I think I have fixed the issue by modifying the project.toml and dependencies for the plotly package, thanks!

**Comment by zsunberg** [comment]
@felixmg312 great! Do you think you could submit a PR with the fixes? That would be very helpful for anyone who uses this package.
